;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        backward-up-list
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        convert-to-underscore
        electric-newline-and-maybe-indent
        forward-sexp
        handle-switch-frame
        haskell-indentation-common-electric-command
        indent-for-tab-command
        isearch-backward-regexp
        isearch-delete-char
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        mark-sexp
        nxml-electric-slash
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        orgtbl-self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        web-mode-comment-indent-new-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        elscreen-previous
        end-of-buffer
        helm-M-x
        helm-confirm-and-exit-minibuffer
        isearch-abort
        isearch-exit
        yas-expand
        ))
