;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        backward-up-list
        electric-newline-and-maybe-indent
        forward-sexp
        isearch-backward-regexp
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-yank
        orgtbl-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        isearch-abort
        isearch-delete-char
        yas-expand
        ))
